"""Read the *real* engine's state back out of a vanilla savegame.

Why: we want machine-checkable evidence that a generated WAD + demo produces a
specific game state, without screenshots or video.  A demo ticcmd can carry
``BT_SPECIAL | BTS_SAVEGAME | slot<<4`` (src/doom/g_game.c:1017-1048), so the
*engine itself* dumps its state at a chosen tic.  The vanilla savegame layout is
written by P_WriteSaveGameHeader / P_ArchiveWorld (src/doom/p_saveg.c:1344,
1481):

    SAVESTRINGSIZE bytes description
    VERSIONSIZE   bytes "version 109"
    u8 gameskill, u8 gameepisode, u8 gamemap
    u8 playeringame[4]
    u24 leveltime
    players (player_t, in-game players only)
    world:   sectors: 7 x i16  (floorheight>>16, ceilingheight>>16, floorpic,
                          ceilingpic, lightlevel, special, tag)
             lines:   3 x i16 + (5 x i16 per valid sidedef)
    thinkers, specials, SAVEGAME_EOF(0x1d)

We do not replicate the player struct: instead we locate the sector array by its
*immutable* per-sector fingerprint (floorpic, ceilingpic, lightlevel, special,
tag) at stride 14, then read back floor/ceiling heights. This is a partial
world-state observation, NOT a complete state hash or a verified Rule 110 tape.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

SAVESTRINGSIZE = 24
VERSIONSIZE = 16
SAVEGAME_EOF = 0x1D
SECTOR_STRIDE = 14
IMMUTABLE_OFFSET = 4  # floorpic starts 4 bytes into a sector record
IMMUTABLE_LEN = 10  # floorpic, ceilingpic, lightlevel, special, tag


@dataclass
class Savegame:
    raw: bytes
    skill: int
    episode: int
    map: int
    playeringame: List[int]
    leveltime: int
    sector_offset: int
    numsectors: int
    floorheights: List[int]
    ceilingheights: List[int]
    floorpics: List[int]
    ceilingpics: List[int]
    lightlevels: List[int]
    specials: List[int]
    tags: List[int]

    def state_hash(self, indices: Optional[Sequence[int]] = None) -> str:
        """Hash of the recovered tape state (floor heights), for the test-suite."""
        import hashlib

        idx = list(range(self.numsectors)) if indices is None else list(indices)
        blob = struct.pack("<" + "i" * len(idx), *[self.floorheights[i] for i in idx])
        return hashlib.sha256(blob).hexdigest()


def _u16(b: bytes, off: int) -> int:
    return struct.unpack_from("<H", b, off)[0]


def _i16(b: bytes, off: int) -> int:
    return struct.unpack_from("<h", b, off)[0]


def parse_savegame(
    blob: bytes,
    expected_fingerprints: Optional[Sequence[Tuple[int, int, int, int, int]]] = None,
    numsectors: Optional[int] = None,
) -> Savegame:
    """Parse a vanilla savegame.

    ``expected_fingerprints`` = per-sector (floorpic, ceilingpic, lightlevel,
    special, tag) as generated by doomc; used to locate + validate the sector
    array.  ``numsectors`` bounds the scan.
    """
    if len(blob) < SAVESTRINGSIZE + VERSIONSIZE + 10:
        raise ValueError("savegame too short")
    ver = blob[SAVESTRINGSIZE : SAVESTRINGSIZE + VERSIONSIZE]
    if not ver.startswith(b"version"):
        raise ValueError(f"unexpected savegame version string {ver!r}")
    p = SAVESTRINGSIZE + VERSIONSIZE
    skill, episode, map_ = blob[p], blob[p + 1], blob[p + 2]
    p += 3
    playeringame = list(blob[p : p + 4])
    p += 4
    leveltime = (blob[p] << 16) | (blob[p + 1] << 8) | blob[p + 2]

    if expected_fingerprints is None:
        raise ValueError("expected_fingerprints are required to locate the world data")

    n = numsectors if numsectors is not None else len(expected_fingerprints)
    if n < 1 or n != len(expected_fingerprints):
        raise ValueError("fingerprint count must match positive numsectors")
    pattern = struct.pack("<5H", *expected_fingerprints[0])
    # search for the fingerprint run, checking the stride-14 replication
    offset = -1
    start = p
    while True:
        cand = blob.find(pattern, start)
        if cand < 0:
            break
        base = cand - IMMUTABLE_OFFSET
        ok = base >= start
        if ok:
            for i in range(n):
                rec = base + i * SECTOR_STRIDE
                if rec + SECTOR_STRIDE > len(blob):
                    ok = False
                    break
                got = struct.unpack_from("<5H", blob, rec + IMMUTABLE_OFFSET)
                if tuple(got) != tuple(expected_fingerprints[i][:5]):
                    ok = False
                    break
        if ok:
            offset = base
            break
        start = cand + 1
    if offset < 0:
        raise ValueError("could not locate the sector array in the savegame")

    floor, ceil, fpic, cpic, light, spec, tag = [], [], [], [], [], [], []
    for i in range(n):
        rec = offset + i * SECTOR_STRIDE
        floor.append(_i16(blob, rec))
        ceil.append(_i16(blob, rec + 2))
        fpic.append(_u16(blob, rec + 4))
        cpic.append(_u16(blob, rec + 6))
        light.append(_u16(blob, rec + 8))
        spec.append(_u16(blob, rec + 10))
        tag.append(_u16(blob, rec + 12))

    return Savegame(
        raw=blob,
        skill=skill,
        episode=episode,
        map=map_,
        playeringame=playeringame,
        leveltime=leveltime,
        sector_offset=offset,
        numsectors=n,
        floorheights=floor,
        ceilingheights=ceil,
        floorpics=fpic,
        ceilingpics=cpic,
        lightlevels=light,
        specials=spec,
        tags=tag,
    )